// <auto-generated />
using API_Gasolina.GasolinaAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Gasolina.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20221013170602_AdicaoCotacaoPosto")]
    partial class AdicaoCotacaoPosto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API_Gasolina.GasolinaAPI.Model.Avaliacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Data")
                        .HasColumnType("longtext")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext")
                        .HasColumnName("descricao");

                    b.Property<string>("IdUsuarioTelegram")
                        .HasColumnType("longtext")
                        .HasColumnName("idusuariotelegram");

                    b.Property<int>("Nota")
                        .HasColumnType("int")
                        .HasColumnName("nota");

                    b.HasKey("Id");

                    b.ToTable("avaliacao");
                });

            modelBuilder.Entity("API_Gasolina.GasolinaAPI.Model.Registro_cotacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Data")
                        .HasColumnType("longtext")
                        .HasColumnName("data");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext")
                        .HasColumnName("estado");

                    b.Property<string>("Municipio")
                        .HasColumnType("longtext")
                        .HasColumnName("municipio");

                    b.Property<int>("Numero_de_postos_pesquisados")
                        .HasColumnType("int")
                        .HasColumnName("numero_de_postos_pesquisados");

                    b.Property<double>("Preco_maximo_revenda")
                        .HasColumnType("double")
                        .HasColumnName("preco_maximo_revenda");

                    b.Property<double>("Preco_medio_revenda")
                        .HasColumnType("double")
                        .HasColumnName("preco_medio_revenda");

                    b.Property<double>("Preco_minimo_revenda")
                        .HasColumnType("double")
                        .HasColumnName("preco_minimo_revenda");

                    b.Property<string>("Produto")
                        .HasColumnType("longtext")
                        .HasColumnName("produto");

                    b.HasKey("Id");

                    b.ToTable("registro_cotacao");
                });

            modelBuilder.Entity("API_Gasolina.Model.Registro_cotacao_posto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Bairro_endereco")
                        .HasColumnType("longtext")
                        .HasColumnName("bairro_endereco");

                    b.Property<string>("Bandeira_posto")
                        .HasColumnType("longtext")
                        .HasColumnName("bandeira_posto");

                    b.Property<int>("Cep_endereco")
                        .HasColumnType("int")
                        .HasColumnName("cep_endereco");

                    b.Property<string>("Cnpj")
                        .HasColumnType("longtext")
                        .HasColumnName("cnpj");

                    b.Property<string>("Complemento_endereco")
                        .HasColumnType("longtext")
                        .HasColumnName("complemento_endereco");

                    b.Property<double>("Cotacao_produto_posto")
                        .HasColumnType("double")
                        .HasColumnName("cotacao_produto_posto");

                    b.Property<string>("Data_coleta_cotacao")
                        .HasColumnType("longtext")
                        .HasColumnName("data_coleta_cotacao");

                    b.Property<string>("Data_cotacao")
                        .HasColumnType("longtext")
                        .HasColumnName("data_cotacao");

                    b.Property<string>("Estado_endereco")
                        .HasColumnType("longtext")
                        .HasColumnName("estado_endereco");

                    b.Property<string>("Municipio_endereco")
                        .HasColumnType("longtext")
                        .HasColumnName("municipio_endereco");

                    b.Property<string>("Nome_fantasia")
                        .HasColumnType("longtext")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("Nome_produto")
                        .HasColumnType("longtext")
                        .HasColumnName("nome_produto");

                    b.Property<string>("Nome_rua")
                        .HasColumnType("longtext")
                        .HasColumnName("nome_rua");

                    b.Property<string>("Numero_rua")
                        .HasColumnType("longtext")
                        .HasColumnName("numero_rua");

                    b.Property<string>("Telefone_posto")
                        .HasColumnType("longtext")
                        .HasColumnName("telefone_posto");

                    b.HasKey("Id");

                    b.ToTable("registro_cotacao_posto");
                });
#pragma warning restore 612, 618
        }
    }
}
